language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  - LTALLOC_CONFIG=Debug
  - LTALLOC_CONFIG=Release

before_script:
  - cd test
  - mkdir build_$LTALLOC_CONFIG                                                                     
  - cd build_$LTALLOC_CONFIG                                                                        
  - cmake ..                       
  - cmake --build . --config $LTALLOC_CONFIG                                                        

script:
  - cd $TRAVIS_BUILD_DIR/test/build_$LTALLOC_CONFIG        
  - ctest -C $LTALLOC_CONFIG -V || exit 1                
