version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
environment:
  matrix:
  - CMAKE_GENERATOR: Visual Studio 15 2017
  - CMAKE_GENERATOR: Visual Studio 15 2017 Win64
before_build:
- cmd: >-
    cd test

    echo CMAKE_GENERATOR=%CMAKE_GENERATOR%

    mkdir "%CMAKE_GENERATOR%"

    cd "%CMAKE_GENERATOR%"

    cmake .. -G "%CMAKE_GENERATOR%"
build:
  project: test/%CMAKE_GENERATOR%/ltalloc_test.sln
  verbosity: minimal
after_build:
- cmd: ctest -V